<a href="https://colab.research.google.com/github/KanoonGammy/Data-Analytics-and-Data-Science-Tools-and-Programming/blob/main/practice5_use_plotly_to_design_Bangkok_Airbnb_Chart.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import plotly.express as px
import seaborn as sns

data = pd.read_csv('https://raw.githubusercontent.com/KanoonGammy/Data-Analytics-and-Data-Science-Tools-and-Programming/refs/heads/main/Bangkok%2C%20Central%20Thailand%2C%20Thailand.csv')
data.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27934,Condo in Samsen Nai · ★4.85 · 1 bedroom · 1 be...,120437,Nuttee,NaN,Ratchathewi,13.75983,100.54134,Entire home/apt,1937,3,65,2020-01-06,0.48,2,269,0,NaN
1,27979,Rental unit in Bangkok · 1 bedroom · 2 beds · ...,120541,Emy,NaN,Bang Na,13.66818,100.61674,Private room,1338,1,0,NaN,NaN,2,0,0,NaN
2,28745,Rental unit in Bangkok · 1 bedroom · 1 bed · 1...,123784,Familyroom,NaN,Bang Kapi,13.75232,100.62402,Private room,800,60,0,NaN,NaN,1,0,0,NaN
3,35780,Rental unit in Bangkok · ★4.75 · 1 bedroom · 1...,153730,Sirilak,NaN,Din Daeng,13.78823,100.57256,Private room,1286,7,4,2023-04-03,0.05,1,358,2,NaN
4,48736,Rental unit in Bangkok · 1 bedroom · 1 bed · 1...,222005,Athitaya,NaN,Rat Burana,13.68556,100.49535,Private room,1585,3,1,2014-02-03,0.01,1,365,0,NaN

In [5]:
df = data.copy()

In [6]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,27934,Condo in Samsen Nai · ★4.85 · 1 bedroom · 1 be...,120437,Nuttee,NaN,Ratchathewi,13.759830,100.541340,Entire home/apt,1937,3,65,2020-01-06,0.48,2,269,0,NaN
1,27979,Rental unit in Bangkok · 1 bedroom · 2 beds · ...,120541,Emy,NaN,Bang Na,13.668180,100.616740,Private room,1338,1,0,NaN,NaN,2,0,0,NaN
2,28745,Rental unit in Bangkok · 1 bedroom · 1 bed · 1...,123784,Familyroom,NaN,Bang Kapi,13.752320,100.624020,Private room,800,60,0,NaN,NaN,1,0,0,NaN
3,35780,Rental unit in Bangkok · ★4.75 · 1 bedroom · 1...,153730,Sirilak,NaN,Din Daeng,13.788230,100.572560,Private room,1286,7,4,2023-04-03,0.05,1,358,2,NaN
4,48736,Rental unit in Bangkok · 1 bedroom · 1 bed · 1...,222005,Athitaya,NaN,Rat Burana,13.685560,100.495350,Private room,1585,3,1,2014-02-03,0.01,1,365,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18874,921696617815599453,Rental unit in Watthana · ★New · 1 bedroom · 1...,504092494,Lucky,NaN,Vadhana,13.743419,100.560440,Entire home/apt,1720,1,0,NaN,NaN,6,360,0,NaN
18875,921851616373636446,Cabin in Khet Bang Rak · ★New · 2 bedrooms · 3...,224384420,Helen,NaN,Bang Rak,13.723008,100.528359,Entire home/apt,4400,1,0,NaN,NaN,1,266,0,NaN
18876,921983797848851444,Rental unit in Khet Khlong San · ★New · 1 bedr...,123941167,Sukhun,NaN,Khlong San,13.726959,100.509463,Entire home/apt,2800,29,0,NaN,NaN,2,365,0,NaN
18877,922126012028485969,Rental unit in Watthana · ★New · 1 bedroom · 1...,10685770,Yeepoon,NaN,Vadhana,13.742607,100.584940,Entire home/apt,1320,4,0,NaN,NaN,4,37,0,NaN
18878,920151306162707461,Rental unit in Khet Khlong Toei · ★New · 1 bed...,28722261,Christy,NaN,Khlong Toei,13.704347,100.597210,Entire home/apt,1000,4,0,NaN,NaN,6,168,0,NaN